/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MesCommandesRouteImport } from './routes/mes-commandes'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as CommandeConfirmationRouteImport } from './routes/commande.confirmation'
import { Route as ApiPublicPrintfulWebhookRouteImport } from './routes/api/public/printful-webhook'
import { Route as ApiPublicCreateCheckoutRouteImport } from './routes/api/public/create-checkout'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MesCommandesRoute = MesCommandesRouteImport.update({
  id: '/mes-commandes',
  path: '/mes-commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeConfirmationRoute = CommandeConfirmationRouteImport.update({
  id: '/commande/confirmation',
  path: '/commande/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrintfulWebhookRoute =
  ApiPublicPrintfulWebhookRouteImport.update({
    id: '/api/public/printful-webhook',
    path: '/api/public/printful-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateCheckoutRoute = ApiPublicCreateCheckoutRouteImport.update({
  id: '/api/public/create-checkout',
  path: '/api/public/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/checkout': typeof CheckoutRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/panier': typeof PanierRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/api/public/create-checkout': typeof ApiPublicCreateCheckoutRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/checkout': typeof CheckoutRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/panier': typeof PanierRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/api/public/create-checkout': typeof ApiPublicCreateCheckoutRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/cgv': typeof CgvRoute
  '/checkout': typeof CheckoutRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-commandes': typeof MesCommandesRoute
  '/panier': typeof PanierRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/api/public/create-checkout': typeof ApiPublicCreateCheckoutRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgv'
    | '/checkout'
    | '/connexion'
    | '/contact'
    | '/inscription'
    | '/mentions-legales'
    | '/mes-commandes'
    | '/panier'
    | '/politique-de-confidentialite'
    | '/commande/confirmation'
    | '/produit/$slug'
    | '/api/public/create-checkout'
    | '/api/public/printful-webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgv'
    | '/checkout'
    | '/connexion'
    | '/contact'
    | '/inscription'
    | '/mentions-legales'
    | '/mes-commandes'
    | '/panier'
    | '/politique-de-confidentialite'
    | '/commande/confirmation'
    | '/produit/$slug'
    | '/api/public/create-checkout'
    | '/api/public/printful-webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/cgv'
    | '/checkout'
    | '/connexion'
    | '/contact'
    | '/inscription'
    | '/mentions-legales'
    | '/mes-commandes'
    | '/panier'
    | '/politique-de-confidentialite'
    | '/commande/confirmation'
    | '/produit/$slug'
    | '/api/public/create-checkout'
    | '/api/public/printful-webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CgvRoute: typeof CgvRoute
  CheckoutRoute: typeof CheckoutRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesCommandesRoute: typeof MesCommandesRoute
  PanierRoute: typeof PanierRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  CommandeConfirmationRoute: typeof CommandeConfirmationRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  ApiPublicCreateCheckoutRoute: typeof ApiPublicCreateCheckoutRoute
  ApiPublicPrintfulWebhookRoute: typeof ApiPublicPrintfulWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-commandes': {
      id: '/mes-commandes'
      path: '/mes-commandes'
      fullPath: '/mes-commandes'
      preLoaderRoute: typeof MesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/confirmation': {
      id: '/commande/confirmation'
      path: '/commande/confirmation'
      fullPath: '/commande/confirmation'
      preLoaderRoute: typeof CommandeConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/printful-webhook': {
      id: '/api/public/printful-webhook'
      path: '/api/public/printful-webhook'
      fullPath: '/api/public/printful-webhook'
      preLoaderRoute: typeof ApiPublicPrintfulWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-checkout': {
      id: '/api/public/create-checkout'
      path: '/api/public/create-checkout'
      fullPath: '/api/public/create-checkout'
      preLoaderRoute: typeof ApiPublicCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  CgvRoute: CgvRoute,
  CheckoutRoute: CheckoutRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesCommandesRoute: MesCommandesRoute,
  PanierRoute: PanierRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  CommandeConfirmationRoute: CommandeConfirmationRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  ApiPublicCreateCheckoutRoute: ApiPublicCreateCheckoutRoute,
  ApiPublicPrintfulWebhookRoute: ApiPublicPrintfulWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
